---
output:
  pdf_document: default
  html_document: default
---

STATS 207 Project RMD

```{r}
library(astsa)
library(Metrics)
library(xts)
library(dlm)
library(ggplot2)
library(TSstudio)

## Import data and preprocess data
## We use the closing data here
## For Kalman filtering specifically, use monthly close intervals rather than daily ones
## Test sample over the most recent six months
full_ark <- read.csv('ARKGMONTH.csv')
fulla_ts <- as.ts(full_ark$Close, full_ark$Date)

full_qqq <- read.csv('QQQMONTH.csv')
fullq_ts <- as.ts(full_qqq$Close, full_qqq$Date)

full_schf <- read.csv('SCHFMONTH.csv')
fulls_ts <- as.ts(full_schf$Close, full_schf$Date)

full_vt <- read.csv('VTMONTH.csv')
fullv_ts <- as.ts(full_vt$Close, full_vt$Date)

full_xlf <- read.csv('XLFMONTH.csv')
fullx_ts <- as.ts(full_xlf$Close, full_xlf$Date)
```

```{r}
## Kalman Filtering for ARKG Data
split_df <- ts_split(ts.obj = fulla_ts, sample.out = 6)

training = split_df$train

model <- function(p) {
  return(dlmModPoly(2, dV = p[1], dW = p[2:3]) + dlmModSeas(12, dV = p[4]))
}

## Parameter Estimation
mle <- dlmMLE(training, parm = c(0.1,0.001,1,1), build = model)
if (mle$convergence == 0) print ('converge') else print('nonconverge')
mle$par
modelfit = model(mle$par)

## Filtering and Smoothing
modelfilter <- dlmFilter(training, modelfit)
modelsmoothed <- dlmSmooth(training, modelfit)
```

```{r}
n <- 1*6
a6_forecast <- dlmForecast(modelfilter, nAhead = n)

x <- index(training)
xf <- seq(max(x), max(x) + n/12, 1/12)
aa <- a6_forecast$a[,1]* (-1)
aa <- cbind(a6_forecast$a[,1], aa)
a <- drop(a6_forecast$a%*%t(FF(modelfit)))
a <- c(tail(training, 1), a)
df <- rbind(
  data.frame(x = x, y = as.numeric(training), series = "original"),
  data.frame(x = x, y = apply(modelfilter$m[-1,1:2],1,sum), series = "filtered"),
  data.frame(x = x, y = apply(modelsmoothed$s[-1,1:2],1,sum), series = "smoothed"),
  data.frame(x = xf, y = a, series = "forecast")
)

dlm <- ggplot(subset(df, x > 48), aes(x=x, y=y, colour = series)) + geom_line()
dlm

data_zoo <- as.zoo(fulla_ts)
actual <- as.vector(data_zoo[(length(data_zoo)-5):length(data_zoo)])
predicted <- as.vector(a6_forecast$f)
sqrt(mse(actual, predicted))
```

```{r}
n <- 1*30
a30_forecast <- dlmForecast(modelfilter, nAhead = n)

x <- index(training)
xf <- seq(max(x), max(x) + n/12, 1/12)
aa <- a30_forecast$a[,1]* (-1)
aa <- cbind(a30_forecast$a[,1], aa)
a <- drop(a30_forecast$a%*%t(FF(modelfit)))
a <- c(tail(training, 1), a)
df <- rbind(
  data.frame(x = x, y = as.numeric(training), series = "original"),
  data.frame(x = x, y = apply(modelfilter$m[-1,1:2],1,sum), series = "filtered"),
  data.frame(x = x, y = apply(modelsmoothed$s[-1,1:2],1,sum), series = "smoothed"),
  data.frame(x = xf, y = a, series = "forecast")
)

dlm <- ggplot(subset(df, x > 48), aes(x=x, y=y, colour = series)) + geom_line()
dlm
```

```{r}
## Kalman Filtering for ARKG Data
split_df <- ts_split(ts.obj = fullq_ts, sample.out = 6)

training = split_df$train

model <- function(p) {
  return(dlmModPoly(2, dV = p[1], dW = p[2:3]) + dlmModSeas(12, dV = p[4]))
}

## Parameter Estimation
mle <- dlmMLE(training, parm = c(0.1,0.001,1,1), build = model)
if (mle$convergence == 0) print ('converge') else print('nonconverge')
mle$par
modelfit = model(mle$par)

## Filtering and Smoothing
modelfilter <- dlmFilter(training, modelfit)
modelsmoothed <- dlmSmooth(training, modelfit)
```

```{r}
n <- 1*6
a6_forecast <- dlmForecast(modelfilter, nAhead = n)

x <- index(training)
xf <- seq(max(x), max(x) + n/12, 1/12)
aa <- a6_forecast$a[,1]* (-1)
aa <- cbind(a6_forecast$a[,1], aa)
a <- drop(a6_forecast$a%*%t(FF(modelfit)))
a <- c(tail(training, 1), a)
df <- rbind(
  data.frame(x = x, y = as.numeric(training), series = "original"),
  data.frame(x = x, y = apply(modelfilter$m[-1,1:2],1,sum), series = "filtered"),
  data.frame(x = x, y = apply(modelsmoothed$s[-1,1:2],1,sum), series = "smoothed"),
  data.frame(x = xf, y = a, series = "forecast")
)

dlm <- ggplot(subset(df, x > 48), aes(x=x, y=y, colour = series)) + geom_line()
dlm

data_zoo <- as.zoo(fullq_ts)
actual <- as.vector(data_zoo[(length(data_zoo)-5):length(data_zoo)])
predicted <- as.vector(a6_forecast$f)
sqrt(mse(actual, predicted))
```

```{r}
n <- 1*30
a30_forecast <- dlmForecast(modelfilter, nAhead = n)

x <- index(training)
xf <- seq(max(x), max(x) + n/12, 1/12)
aa <- a30_forecast$a[,1]* (-1)
aa <- cbind(a30_forecast$a[,1], aa)
a <- drop(a30_forecast$a%*%t(FF(modelfit)))
a <- c(tail(training, 1), a)
df <- rbind(
  data.frame(x = x, y = as.numeric(training), series = "original"),
  data.frame(x = x, y = apply(modelfilter$m[-1,1:2],1,sum), series = "filtered"),
  data.frame(x = x, y = apply(modelsmoothed$s[-1,1:2],1,sum), series = "smoothed"),
  data.frame(x = xf, y = a, series = "forecast")
)

dlm <- ggplot(subset(df, x > 48), aes(x=x, y=y, colour = series)) + geom_line()
dlm
```

```{r}
## Kalman Filtering for ARKG Data
split_df <- ts_split(ts.obj = fulla_ts, sample.out = 6)

training = split_df$train

model <- function(p) {
  return(dlmModPoly(2, dV = p[1], dW = p[2:3]) + dlmModSeas(12, dV = p[4]))
}

## Parameter Estimation
mle <- dlmMLE(training, parm = c(0.1,0.001,1,1), build = model)
if (mle$convergence == 0) print ('converge') else print('nonconverge')
mle$par
modelfit = model(mle$par)

## Filtering and Smoothing
modelfilter <- dlmFilter(training, modelfit)
modelsmoothed <- dlmSmooth(training, modelfit)
```

```{r}
n <- 1*6
a6_forecast <- dlmForecast(modelfilter, nAhead = n)

x <- index(training)
xf <- seq(max(x), max(x) + n/12, 1/12)
aa <- a6_forecast$a[,1]* (-1)
aa <- cbind(a6_forecast$a[,1], aa)
a <- drop(a6_forecast$a%*%t(FF(modelfit)))
a <- c(tail(training, 1), a)
df <- rbind(
  data.frame(x = x, y = as.numeric(training), series = "original"),
  data.frame(x = x, y = apply(modelfilter$m[-1,1:2],1,sum), series = "filtered"),
  data.frame(x = x, y = apply(modelsmoothed$s[-1,1:2],1,sum), series = "smoothed"),
  data.frame(x = xf, y = a, series = "forecast")
)

dlm <- ggplot(subset(df, x > 48), aes(x=x, y=y, colour = series)) + geom_line()
dlm

data_zoo <- as.zoo(fulla_ts)
actual <- as.vector(data_zoo[(length(data_zoo)-5):length(data_zoo)])
predicted <- as.vector(a6_forecast$f)
sqrt(mse(actual, predicted))
```

```{r}
n <- 1*30
a30_forecast <- dlmForecast(modelfilter, nAhead = n)

x <- index(training)
xf <- seq(max(x), max(x) + n/12, 1/12)
aa <- a30_forecast$a[,1]* (-1)
aa <- cbind(a30_forecast$a[,1], aa)
a <- drop(a30_forecast$a%*%t(FF(modelfit)))
a <- c(tail(training, 1), a)
df <- rbind(
  data.frame(x = x, y = as.numeric(training), series = "original"),
  data.frame(x = x, y = apply(modelfilter$m[-1,1:2],1,sum), series = "filtered"),
  data.frame(x = x, y = apply(modelsmoothed$s[-1,1:2],1,sum), series = "smoothed"),
  data.frame(x = xf, y = a, series = "forecast")
)

dlm <- ggplot(subset(df, x > 48), aes(x=x, y=y, colour = series)) + geom_line()
dlm

a30_forecast$f
```

```{r}
## Kalman Filtering for QQQ Data
split_df <- ts_split(ts.obj = fullq_ts, sample.out = 6)

training = split_df$train

model <- function(p) {
  return(dlmModPoly(2, dV = p[1], dW = p[2:3]) + dlmModSeas(12, dV = p[4]))
}

## Parameter Estimation
mle <- dlmMLE(training, parm = c(0.1,0.001,1,1), build = model)
if (mle$convergence == 0) print ('converge') else print('nonconverge')
mle$par
modelfit = model(mle$par)

## Filtering and Smoothing
modelfilter <- dlmFilter(training, modelfit)
modelsmoothed <- dlmSmooth(training, modelfit)
```

```{r}
n <- 1*6
a6_forecast <- dlmForecast(modelfilter, nAhead = n)

x <- index(training)
xf <- seq(max(x), max(x) + n/12, 1/12)
aa <- a6_forecast$a[,1]* (-1)
aa <- cbind(a6_forecast$a[,1], aa)
a <- drop(a6_forecast$a%*%t(FF(modelfit)))
a <- c(tail(training, 1), a)
df <- rbind(
  data.frame(x = x, y = as.numeric(training), series = "original"),
  data.frame(x = x, y = apply(modelfilter$m[-1,1:2],1,sum), series = "filtered"),
  data.frame(x = x, y = apply(modelsmoothed$s[-1,1:2],1,sum), series = "smoothed"),
  data.frame(x = xf, y = a, series = "forecast")
)

dlm <- ggplot(subset(df, x > 48), aes(x=x, y=y, colour = series)) + geom_line()
dlm

data_zoo <- as.zoo(fullq_ts)
actual <- as.vector(data_zoo[(length(data_zoo)-5):length(data_zoo)])
predicted <- as.vector(a6_forecast$f)
sqrt(mse(actual, predicted))
```

```{r}
n <- 1*30
a30_forecast <- dlmForecast(modelfilter, nAhead = n)

x <- index(training)
xf <- seq(max(x), max(x) + n/12, 1/12)
aa <- a30_forecast$a[,1]* (-1)
aa <- cbind(a30_forecast$a[,1], aa)
a <- drop(a30_forecast$a%*%t(FF(modelfit)))
a <- c(tail(training, 1), a)
df <- rbind(
  data.frame(x = x, y = as.numeric(training), series = "original"),
  data.frame(x = x, y = apply(modelfilter$m[-1,1:2],1,sum), series = "filtered"),
  data.frame(x = x, y = apply(modelsmoothed$s[-1,1:2],1,sum), series = "smoothed"),
  data.frame(x = xf, y = a, series = "forecast")
)

dlm <- ggplot(subset(df, x > 48), aes(x=x, y=y, colour = series)) + geom_line()
dlm

a30_forecast$f
```

```{r}
## Kalman Filtering for SCHF Data
split_df <- ts_split(ts.obj = fulls_ts, sample.out = 6)

training = split_df$train

model <- function(p) {
  return(dlmModPoly(2, dV = p[1], dW = p[2:3]) + dlmModSeas(12, dV = p[4]))
}

## Parameter Estimation
mle <- dlmMLE(training, parm = c(0.1,0.001,1,1), build = model)
if (mle$convergence == 0) print ('converge') else print('nonconverge')
mle$par
modelfit = model(mle$par)

## Filtering and Smoothing
modelfilter <- dlmFilter(training, modelfit)
modelsmoothed <- dlmSmooth(training, modelfit)
```

```{r}
n <- 1*6
a6_forecast <- dlmForecast(modelfilter, nAhead = n)

x <- index(training)
xf <- seq(max(x), max(x) + n/12, 1/12)
aa <- a6_forecast$a[,1]* (-1)
aa <- cbind(a6_forecast$a[,1], aa)
a <- drop(a6_forecast$a%*%t(FF(modelfit)))
a <- c(tail(training, 1), a)
df <- rbind(
  data.frame(x = x, y = as.numeric(training), series = "original"),
  data.frame(x = x, y = apply(modelfilter$m[-1,1:2],1,sum), series = "filtered"),
  data.frame(x = x, y = apply(modelsmoothed$s[-1,1:2],1,sum), series = "smoothed"),
  data.frame(x = xf, y = a, series = "forecast")
)

dlm <- ggplot(subset(df, x > 48), aes(x=x, y=y, colour = series)) + geom_line()
dlm

data_zoo <- as.zoo(fulls_ts)
actual <- as.vector(data_zoo[(length(data_zoo)-5):length(data_zoo)])
predicted <- as.vector(a6_forecast$f)
sqrt(mse(actual, predicted))
```

```{r}
n <- 1*30
a30_forecast <- dlmForecast(modelfilter, nAhead = n)

x <- index(training)
xf <- seq(max(x), max(x) + n/12, 1/12)
aa <- a30_forecast$a[,1]* (-1)
aa <- cbind(a30_forecast$a[,1], aa)
a <- drop(a30_forecast$a%*%t(FF(modelfit)))
a <- c(tail(training, 1), a)
df <- rbind(
  data.frame(x = x, y = as.numeric(training), series = "original"),
  data.frame(x = x, y = apply(modelfilter$m[-1,1:2],1,sum), series = "filtered"),
  data.frame(x = x, y = apply(modelsmoothed$s[-1,1:2],1,sum), series = "smoothed"),
  data.frame(x = xf, y = a, series = "forecast")
)

dlm <- ggplot(subset(df, x > 48), aes(x=x, y=y, colour = series)) + geom_line()
dlm

a30_forecast$f
```

```{r}
## Kalman Filtering for VT Data
split_df <- ts_split(ts.obj = fullv_ts, sample.out = 6)

training = split_df$train

model <- function(p) {
  return(dlmModPoly(2, dV = p[1], dW = p[2:3]) + dlmModSeas(12, dV = p[4]))
}

## Parameter Estimation
mle <- dlmMLE(training, parm = c(0.1,0.001,1,1), build = model)
if (mle$convergence == 0) print ('converge') else print('nonconverge')
mle$par
modelfit = model(mle$par)

## Filtering and Smoothing
modelfilter <- dlmFilter(training, modelfit)
modelsmoothed <- dlmSmooth(training, modelfit)
```

```{r}
n <- 1*6
a6_forecast <- dlmForecast(modelfilter, nAhead = n)

x <- index(training)
xf <- seq(max(x), max(x) + n/12, 1/12)
aa <- a6_forecast$a[,1]* (-1)
aa <- cbind(a6_forecast$a[,1], aa)
a <- drop(a6_forecast$a%*%t(FF(modelfit)))
a <- c(tail(training, 1), a)
df <- rbind(
  data.frame(x = x, y = as.numeric(training), series = "original"),
  data.frame(x = x, y = apply(modelfilter$m[-1,1:2],1,sum), series = "filtered"),
  data.frame(x = x, y = apply(modelsmoothed$s[-1,1:2],1,sum), series = "smoothed"),
  data.frame(x = xf, y = a, series = "forecast")
)

dlm <- ggplot(subset(df, x > 48), aes(x=x, y=y, colour = series)) + geom_line()
dlm

data_zoo <- as.zoo(fullv_ts)
actual <- as.vector(data_zoo[(length(data_zoo)-5):length(data_zoo)])
predicted <- as.vector(a6_forecast$f)
sqrt(mse(actual, predicted))
```

```{r}
n <- 1*30
a30_forecast <- dlmForecast(modelfilter, nAhead = n)

x <- index(training)
xf <- seq(max(x), max(x) + n/12, 1/12)
aa <- a30_forecast$a[,1]* (-1)
aa <- cbind(a30_forecast$a[,1], aa)
a <- drop(a30_forecast$a%*%t(FF(modelfit)))
a <- c(tail(training, 1), a)
df <- rbind(
  data.frame(x = x, y = as.numeric(training), series = "original"),
  data.frame(x = x, y = apply(modelfilter$m[-1,1:2],1,sum), series = "filtered"),
  data.frame(x = x, y = apply(modelsmoothed$s[-1,1:2],1,sum), series = "smoothed"),
  data.frame(x = xf, y = a, series = "forecast")
)

dlm <- ggplot(subset(df, x > 48), aes(x=x, y=y, colour = series)) + geom_line()
dlm

a30_forecast$f
```

```{r}
## Kalman Filtering for XLF Data
split_df <- ts_split(ts.obj = fullx_ts, sample.out = 6)

training = split_df$train

model <- function(p) {
  return(dlmModPoly(2, dV = p[1], dW = p[2:3]) + dlmModSeas(12, dV = p[4]))
}

## Parameter Estimation
mle <- dlmMLE(training, parm = c(0.1,0.001,1,1), build = model)
if (mle$convergence == 0) print ('converge') else print('nonconverge')
mle$par
modelfit = model(mle$par)

## Filtering and Smoothing
modelfilter <- dlmFilter(training, modelfit)
modelsmoothed <- dlmSmooth(training, modelfit)
```

```{r}
n <- 1*6
a6_forecast <- dlmForecast(modelfilter, nAhead = n)

x <- index(training)
xf <- seq(max(x), max(x) + n/12, 1/12)
aa <- a6_forecast$a[,1]* (-1)
aa <- cbind(a6_forecast$a[,1], aa)
a <- drop(a6_forecast$a%*%t(FF(modelfit)))
a <- c(tail(training, 1), a)
df <- rbind(
  data.frame(x = x, y = as.numeric(training), series = "original"),
  data.frame(x = x, y = apply(modelfilter$m[-1,1:2],1,sum), series = "filtered"),
  data.frame(x = x, y = apply(modelsmoothed$s[-1,1:2],1,sum), series = "smoothed"),
  data.frame(x = xf, y = a, series = "forecast")
)

dlm <- ggplot(subset(df, x > 48), aes(x=x, y=y, colour = series)) + geom_line()
dlm

data_zoo <- as.zoo(fullx_ts)
actual <- as.vector(data_zoo[(length(data_zoo)-5):length(data_zoo)])
predicted <- as.vector(a6_forecast$f)
sqrt(mse(actual, predicted))
```

```{r}
n <- 1*30
a30_forecast <- dlmForecast(modelfilter, nAhead = n)

x <- index(training)
xf <- seq(max(x), max(x) + n/12, 1/12)
aa <- a30_forecast$a[,1]* (-1)
aa <- cbind(a30_forecast$a[,1], aa)
a <- drop(a30_forecast$a%*%t(FF(modelfit)))
a <- c(tail(training, 1), a)
df <- rbind(
  data.frame(x = x, y = as.numeric(training), series = "original"),
  data.frame(x = x, y = apply(modelfilter$m[-1,1:2],1,sum), series = "filtered"),
  data.frame(x = x, y = apply(modelsmoothed$s[-1,1:2],1,sum), series = "smoothed"),
  data.frame(x = xf, y = a, series = "forecast")
)

dlm <- ggplot(subset(df, x > 48), aes(x=x, y=y, colour = series)) + geom_line()
dlm

a30_forecast$f
```